version: "3.8"

volumes:
  web_data:
    external: true
  postgres_data:
    external: true
  geoserver_data:
    external: true

services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8082:80"
    volumes:
      - /Users/aaryn/personal/asdm/data/imagery/:/usr/share/nginx/html
  # geoserver:
  #   image: "docker.osgeo.org/geoserver:2.23.1"
  #   hostname: geoserver
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - geoserver_data:/opt/geoserver/data_dir
  #     - /Users/aaryn/personal/asdm/data/imagery:/imagery
  #   environment:
  #     # - GEOSERVER_ADMIN_USER=admin
  #     # - GEOSERVER_ADMIN_PASSWORD=geoserver
  #     # # - HTTP_PROXY_NAME=${CODESPACE_NAME}-8080.preview.app.github.dev
  #     # - HTTP_SCHEME=http
  #     # - COMMUNITY_EXTENSIONS=jp2k-plugin
  #     # - ROOT_WEBAPP_REDIRECT=true
  #     # - MAXIMUM_MEMORY=756M
  #     # - INITIAL_MEMORY=128M
  #     - INSTALL_EXTENSIONS=true
  #     - STABLE_EXTENSIONS=pyramid
  #     - SKIP_DEMO_DATA=true
  #     - CORS_ENABLED=true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 8G
  #       reservations:
  #         cpus: '1'
  #         memory: 1G

networks:
  default:
    name: asdm
